data_path: '../../data/fishing.db'
date_columns : ["Date", "Day", "Month", "Year"]
target : 'RainTomorrow'
model_1:
  model_name: 'RandomForest'
  model_save_loc: models/rf_model.sav
  is_train: True
  save_model: True
  output_path: rf_prediction.csv
  log_path: logs/
  plot_path: plots/
  rf_n_est: [800, 1001, 100]
  rf_max_d: [6, 9, 1]
  threshold: 0.5
model_2:
  model_name: 'XGBoost'
  model_save_loc: models/xgboost_model.sav
  is_train: True
  save_model: True
  output_path: xgboost_prediction.csv
  log_path: logs/
  plot_path: plots/
  xgb_eta: [0.10, 0.20, 0.05]
  xgb_max_d: [4, 6, 1]
  xgb_min_weight: [10, 14, 2]
  xgb_n_est: [600, 801, 100]
  xgb_sample: [0.7, 0.91, 0.1]
  threshold: 0.5
model_3:
  model_name: 'KNN'
  model_save_loc: models/knn.sav
  is_train: True
  save_model: True
  output_path: knn_prediction.csv
  log_path: logs/
  plot_path: plots/
  'n_neighbors': [3, 5, 7, 9] 
  'weights': ['uniform', 'distance']
  'p': [1, 2, 3]
  threshold: 0.5